### ISSUE TITLE
AttributeError: 'LayerParameter' object has no attribute ...

### ISSUE THREAD

**Issue by ThomasLecat** [junhyukoh/nips2015-action-conditional-video-prediction#6]
Hi Junhyuk,
Thanks for the code! 
I finally managed to compile caffe but now I have some errors when trying to train the network, both for the cnn and the lstm versions.

For the cnn version, I have : 
`data`
`act`
`x_flat`
`Traceback (most recent call last):`
  `File "../train.py", line 105, in <module>`
    `  main(**vars(args))`
  `File "../train.py", line 52, in main`
    `  load_to_mem=load_to_mem)`
  `File "/homes/tjl16/Software/junhyukoh_action/net.py", line 343, in create_netfile`
    `  load_to_mem=load_to_mem, mode=mode)`
  `File "/homes/tjl16/Software/junhyukoh_action/net.py", line 215, in cnn_proto`
    `  return n.to_proto()`
  `File "/homes/tjl16/Software/junhyukoh_action/caffe/python/caffe/net_spec.py", line 201, in to_proto`
    `  top._to_proto(layers, names, autonames)`
  `File "/homes/tjl16/Software/junhyukoh_action/caffe/python/caffe/net_spec.py", line 97, in _to_proto`
    `  return self.fn._to_proto(layers, names, autonames)`
  `File "/homes/tjl16/Software/junhyukoh_action/caffe/python/caffe/net_spec.py", line 170, in _to_proto`
    `  assign_proto(layer, k, v)`
  `File "/homes/tjl16/Software/junhyukoh_action/caffe/python/caffe/net_spec.py", line 64, in assign_proto`
    `  is_repeated_field = hasattr(getattr(proto, name), 'extend')`
`AttributeError: 'LayerParameter' object has no attribute 'end_axis'`

while for the lstm version, I have :
`data`
`act`
`clip`
`h-00`
`c-00`
`clip_reshape`
`Traceback (most recent call last):`
`  File "../train.py", line 105, in <module>`
`    main(**vars(args))`
`  File "../train.py", line 52, in main`
`    load_to_mem=load_to_mem)`
`  File "/homes/tjl16/Software/junhyukoh_action/net.py", line 346, in create_netfile`
`    load_to_mem=load_to_mem, mode=mode)`
`  File "/homes/tjl16/Software/junhyukoh_action/net.py", line 336, in rnn_proto`
`    return n.to_proto()`
`  File "/homes/tjl16/Software/junhyukoh_action/caffe/python/caffe/net_spec.py", line 201, in to_proto`
`    top._to_proto(layers, names, autonames)`
`  File "/homes/tjl16/Software/junhyukoh_action/caffe/python/caffe/net_spec.py", line 97, in _to_proto`
`    return self.fn._to_proto(layers, names, autonames)`
`  File "/homes/tjl16/Software/junhyukoh_action/caffe/python/caffe/net_spec.py", line 170, in _to_proto`
`    assign_proto(layer, k, v)`
`  File "/homes/tjl16/Software/junhyukoh_action/caffe/python/caffe/net_spec.py", line 64, in assign_proto`
`    is_repeated_field = hasattr(getattr(proto, name), 'extend')`
`AttributeError: 'LayerParameter' object has no attribute 'shape'`

Any idea where does the errors come from and how to avoid them ?
Thanks!

**Comment by memanuel** [comment]
Hi Junhyuk,

Thanks for sharing your code and great job on this paper, it was very interesting.

I've also encountered the exact same issue as Thomas LeCat.  I followed the installation instructions very carefully and am really struggling to track this down.  I'm running on Ubuntu 16.04 LTS.  Caffe installed OK using the current OpenCV (now version 3.3).  There were a few minor compilation and linking issues I was able to fix.   The biggest problem was that std::max(float, double) got confused several templates.  I was able to fix three instances of this problem by replacing them with std::max<Dtype>(float, double).  I know that Caffe has built because it's passing all the self tests. pycaffe builds successfully too, and I'm pretty sure it's OK, because I can type:
`>>> import caffe`
from an interactive Python (2.7) session without complaint.

I navigate to directory /home/action-cond-video-pred/examples and run
`../train_cnn.sh 3 0` 
3 is the number of actions (the action log file has 0, 1, and 2 in it so it looks like there are three available).  and 0 is the GPU ID.
When I do this, I get the exact same error message above as ThomasLecat.
`../train_lstm.sh 3 0`
also gives an identical error message to Thomas.  The contents of the example directory were downloaded from the repo, and they match the specification exactly.

Thomas-- were you ever able to resolve this issue? 
Junhyuk-- any suggestions on how to fix this?

Many thanks!
